---

- name: Ensure all system packages are upgraded
  apt: upgrade=dist update_cache=yes
  tags: packages
  when: system_upgrade is defined and system_upgrade

- name: Install base packages
  apt: name={{ item }} update_cache={{ update_apt_cache }} force=yes state=installed
  with_items:
    - build-essential
    - ntp
    - htop
    - mc
    - git
    - python-dev
    - python-pip
    - python-pycurl
    - supervisor
  tags: packages

- name: Install virtualenv
  pip: name=virtualenv
  tags: packages

- name: sshd stop accepting client's locale
  lineinfile: dest=/etc/ssh/sshd_config state=present regexp="^#?\s*AcceptEnv LANG" line="# AcceptEnv LANG"
#  when:

- name: Set locales to en_US
  shell: update-locale LC_ALL={{ locale }} LANG={{ locale }} LANGUAGE={{ locale }}
